import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import {  Flex } from "@chakra-ui/react";
import {Hero} from '../components/molecules/Hero/Hero'
import { TopBar } from "../components/organisms/TopBar/TopBar";
import { LandingBody } from "../components/organisms/LandingBody/LandingBody";
import { LandingFooter } from "../components/organisms/LendingFooter/LandingFooter";
import { getSession } from "next-auth/react";


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Todo</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://cdn-icons-png.flaticon.com/512/1/1560.png"
        />
      </Head>
      <TopBar/>
      <Flex>
        <Hero />
      </Flex>
      <LandingBody />
      <LandingFooter />
    </div>
  );
};

export default Home;


export async function getServerSideProps(context:any) {
  const session = await getSession(context);
  if (session) {
    return {
      redirect: {
        destination: "/logged",
        permanent: false,
      },
    };
  }
  return {
    props:{},
  };
}
